### ISSUE TITLE
pinefarm requires pinecards to be in a repo

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/pinefarm#12]
@niclaurenti got hit by the following bug:

in https://github.com/NNPDF/runcards/blob/7f11afce4242791acad47d4c7be393e629b5121d/pinefarm/external/interface.py#L114 we require that we are inside an actual repo (as would be in development mode, so when cloning this repo) - not being so, as can happen e.g. upon `pip install pineline[full]` and adding some stand alone cards, results in an exception (@niclaurenti if you still have - please paste the full error here)

I guess we should catch that error and eventually leave the field empty

**Comment by AleCandido** [comment]
This will be solved by #15

**Comment by felixhekhorn** [comment]
Closed via https://github.com/NNPDF/pinefarm/pull/23
