### ISSUE TITLE
Store pinecard in the grid

### ISSUE THREAD

**Issue by AleCandido** [NNPDF/pinefarm#15]
As we decided with @felixhekhorn @cschwan and @scarlehoff, we will stop storing the pinecard version in the grid (or maybe make it optional?), and we will write the full tar-gzipped pinecard (the folder) in the metadata, encoded in a string with `base64`, that is a rather common encoding.

PineAPPL will provide support for extracting the tarball from the metadata (i.e. decode `base64` to bytes, a redirect should do the rest of the job, I guess).

**Comment by felixhekhorn** [comment]
Actually, do we need to act in pineappl at all? can't we just rely on UNIX' `base64`? i.e. something like `pineappl info --get runcard.tar.gz grid.pineappl.lz4 | base64 --decode - > runcard.tar.gz` should work, no? @cschwan

**Comment by cschwan** [comment]
Good catch, @felixhekhorn!

In terms of reproducibility, I was thinking of the following:

```bash
# untars the directory used to crate the grid
pineappl info --get runcards [grid] | base64 --decode | tar xf -

if [[ $(pinefarm --version) != $(pineappl info --get pinefarm_version) ]]; then
    echo "pinefarm version different"
fi

# treat theory settings similarly
pinefarm run [directory-name] [theory-name]

pineappl diff [grid-1] [grid-2] NNPDF31_nnlo_as_0118_luxqed && echo "success!"
```

**Comment by AleCandido** [comment]
> can't we just rely on UNIX' `base64`?

I simply didn't know that `base64` was distributed with GNU coreutils :)

**Comment by cschwan** [comment]
Me neither, but it makes sense considering Email uses it to send attachments.

**Comment by AleCandido** [comment]
> In terms of reproducibility, I was thinking of the following:

I agree on the layout:
- the full snippet should be in the `pinefarm` docs
- the first line we should also add to PineAPPL docs

**Comment by cschwan** [comment]
We can also get rid of the various generator-specific metadata, for instance `output.txt` and `launch.txt` I believe no longer to be relevant.

**Comment by AleCandido** [comment]
Ok, I agree on that. While instead I would keep the unraveled content of `metadata.txt` as it is, that should be common to all the grids.

**Comment by felixhekhorn** [comment]
> We can also get rid of the various generator-specific metadata, for instance `output.txt` and `launch.txt` I believe no longer to be relevant.

Mmm? I have no idea of Mg5, but I believe e.g. https://github.com/NNPDF/runcards/blob/master/pinecards/ATLAS_1JET_8TEV_R06/launch.txt contains relevant pieces of information. Where else is the `#user_defined_cut set atlas_1jet_8tev_r06 = True`?

**Comment by cschwan** [comment]
It would be in the tarball contained in the metadata (and the numerical values in the theory)!

**Comment by AleCandido** [comment]
As @cschwan said, the reproducibility is guaranteed by the tarball.

> Where else is the `#user_defined_cut set atlas_1jet_8tev_r06 = True`?

This kind of data are useful to reproduce, but not extremely meaningful at first inspection. If you ever need to retrieve specifically that information, you can extract the tarball. But I expect it to happen seldom (while meanings of the bins, the observable, or the paper reference are useful to keep at hand).

**Comment by felixhekhorn** [comment]
but then you have to do either
- come up with [a different strategy for reproducing](https://github.com/NNPDF/pinefarm/issues/15#issuecomment-1352889621) because `pinefarm run a b` will no longer work
- or come up with a strategy here: https://github.com/NNPDF/pinefarm/blob/b6993605ef3ab6b5fa711f384d8fdcbf2108c8a7/src/pinefarm/external/mg5/__init__.py#L55

**Comment by AleCandido** [comment]
Not really: the proposal is not to drop `output.txt` from the runcard, but only from grids metadata.

**Comment by felixhekhorn** [comment]
> Not really: the proposal is not to drop `output.txt` from the runcard, but only from grids metadata.

okay - now I understand! yes, I agree
