### ISSUE TITLE
Issue with pinefarm cli, theories and pinecards not listed

### ISSUE THREAD

**Issue by comane** [NNPDF/pinefarm#48]
Hi @cschwan , @felixhekhorn. After installing pinefarm with pip (`pip install pinefarm`) in a fresh conda environment I try to get the list of pinecards and theories. In both cases the command fails:

```
$ pinefarm list theories
^[[1;2D/store/DAMTP/mnc33/miniconda3/envs/pinefarm/lib/python3.9/site-packages/pinefarm/cli/_base.py:26: UserWarning: No configuration file detected.
  warnings.warn("No configuration file detected.")
/store/DAMTP/mnc33/miniconda3/envs/pinefarm/lib/python3.9/site-packages/pinefarm/configs.py:82: UserWarning: Using default minimal configuration ('root = $PWD').
  warnings.warn("Using default minimal configuration ('root = $PWD').")
```

**Comment by felixhekhorn** [comment]
You need a [`pinefarm.toml`](https://github.com/NNPDF/pinefarm/blob/main/pinefarm.toml) file to be able to run

I guess this is once more the prove that we should address https://github.com/NNPDF/pinefarm/issues/4 - your contributions would be very welcome :innocent:

**Comment by felixhekhorn** [comment]
should be addressed by https://github.com/NNPDF/pinefarm/pull/52 - if not please reopen
