### ISSUE TITLE
Polarized integrability

### ISSUE THREAD

**Issue by felixhekhorn** [NNPDF/pinefarm#60]
I'm reopening this PR as I think we should impose integrability on `\Delta f(x)` and not `x \Delta f(x)` as currently implemented. 
See #58

_Originally posted by @giacomomagni in https://github.com/NNPDF/pinefarm/issues/57#issuecomment-1864234226_

**Comment by giacomomagni** [comment]
No wait, I was confused .... I think what we have now it's correct no ?

**Comment by felixhekhorn** [comment]
good - I just was afraid it got lost (I'm still catching up from the holidays :upside_down_face: )
