### ISSUE TITLE
Missing `tomlkit`

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pinefarm#9]
At least on `dom` on the `DIS-more` branch I get:

```
Error processing line 1 of /home/cschwan/.local/lib/python3.10/site-packages/zzz_poetry_dynamic_versioning.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/home/cschwan/.local/lib/python3.10/site-packages/poetry_dynamic_versioning/__init__.py", line 13, in <module>
      import tomlkit
  ModuleNotFoundError: No module named 'tomlkit'
```

**Comment by felixhekhorn** [comment]
this is quite old - is it still an issue @cschwan ? or can we close? if I understood correctly @scarlehoff was able to use the package to reproduce everything ...
cc @AleCandido

**Comment by cschwan** [comment]
I recently installed it somewhere and it wasn't a problem. Let's close it!

**Comment by AleCandido** [comment]
Btw, since py3.11 (that I expect no one is using yet) `tomlkit` is part of Python standard library

**Comment by felixhekhorn** [comment]
interesting :upside_down_face:  
![grafik](https://user-images.githubusercontent.com/6421325/207831281-fa7d4dd3-fdd6-44bd-8475-6c803df1222e.png)

**Comment by cschwan** [comment]
Race condition: github edition.
